print("hello world")
print("who are you")
print("heya ")
print("how are you")
print("i am fine")
print("what is your name")
print("my name is kiran")
print("how old are you")
print("i am 20 years old")
print("where are you from")
print("i am from india")
print("what is your favorite color")
print("my favorite color is blue")
print("what is your favorite food")
print("my favorite food is pizza")
print("what is your favorite sport")
print("my favorite sport is cricket")
print("what is your favorite movie")
print("my favorite movie is avatar")